# Generated by Django 5.2.16 on 2026-07-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Sports', 'Sports'), ('Community', 'Community'), ('Events', 'Events'), ('Volunteers', 'Volunteers'), ('Children', 'Children')], max_length=50)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
